export const API_BASE = "https://api.teamsnap.com/v3";
export const TOKEN_URL = "https://auth.teamsnap.com/oauth/token";

export const ENDPOINTS = {
  me: "/me",
  teams: "/teams/search",
  members: "/members/search",
  memberById: (id: string) => `/members/${id}`,
  events: "/events/search",
  eventsBase: "/events",
  eventById: (id: string) => `/events/${id}`,
  availabilities: "/availabilities/search",
  availabilityById: (id: string) => `/availabilities/${id}`,
  locations: "/locations/search",
  locationById: (id: string) => `/locations/${id}`,
  memberEmails: "/member_email_addresses/search",
  memberPhones: "/member_phone_numbers/search",
  memberPhotos: "/member_photos/search",
  contacts: "/contacts/search",
  contactEmails: "/contact_email_addresses/search",
  contactPhones: "/contact_phone_numbers/search",
  broadcastEmails: "/broadcast_emails/search",
  broadcastEmailsBase: "/broadcast_emails",
  broadcastAlerts: "/broadcast_alerts/search",
  broadcastAlertsBase: "/broadcast_alerts",
  messages: "/messages/search",
  messagesBase: "/messages",
  trackedItems: "/tracked_items/search",
  trackedItemsBase: "/tracked_items",
  trackedItemStatuses: "/tracked_item_statuses/search",
  trackedItemStatusById: (id: string) => `/tracked_item_statuses/${id}`,
  assignments: "/assignments/search",
  assignmentsBase: "/assignments",
  opponents: "/opponents/search",
  opponentsResults: "/opponents_results/search",
  teamResults: "/team_results/search",
  divisionTeamStandings: "/division_team_standings/search",
  statistics: "/statistics/search",
  memberStatistics: "/member_statistics/search",
  eventStatistics: "/event_statistics/search",
  teamStatistics: "/team_statistics/search",
  forumTopics: "/forum_topics/search",
  forumPosts: "/forum_posts/search",
  customFields: "/custom_fields/search",
  customData: "/custom_data/search",
} as const;

export const REL = {
  calendar_http: "calendar_http",
  calendar_http_games_only: "calendar_http_games_only",
  calendar_webcal: "calendar_webcal",
  calendar_webcal_games_only: "calendar_webcal_games_only",
  team_public_site: "team_public_site",
  location: "location",
} as const;
