export const SPORT_NAMES: Record<number, string> = {
  1: "Baseball",
  2: "Basketball",
  3: "Field Hockey",
  4: "Football",
  5: "Golf",
  6: "Gymnastics",
  7: "Hockey",
  8: "Inline Hockey",
  9: "Ice Skating",
  10: "Lacrosse",
  11: "Martial Arts",
  12: "Other Sports",
  13: "Polo",
  14: "Racing",
  15: "Rowing",
  16: "Soccer",
  17: "Softball",
  18: "Swimming",
  19: "Tennis",
  20: "Track & Field",
  21: "Volleyball",
  22: "Water Polo",
  23: "Wrestling",
  24: "Australian Football",
  25: "Auto Racing",
  26: "Badminton",
  27: "Bocce",
  28: "Bowling",
  29: "Cheerleading",
  30: "Cricket",
  31: "Curling",
  32: "Cycling",
  33: "Dance Team",
  34: "Dodgeball",
  35: "Equestrian",
  36: "Fencing",
  37: "Figure Skating",
  38: "Fishing",
  39: "Flag Football",
  40: "Floor Hockey",
  41: "Handball",
  42: "Hurling",
  43: "Judo",
  44: "Kickball",
  45: "Netball",
  46: "Paintball",
  47: "Petanque",
  48: "Pickleball",
  49: "Quidditch",
  50: "Ringette",
  51: "Roller Derby",
  52: "Rugby",
  53: "Sailing",
  54: "Skiing",
  55: "Snowboarding",
  56: "Squash",
  57: "Table Tennis",
  58: "Ultimate Frisbee",
  59: "Unicycling",
  60: "Water Skiing",
};

export function sportName(sportId: number | string | null | undefined): string | null {
  if (sportId == null) return null;
  const id = typeof sportId === "string" ? parseInt(sportId, 10) : sportId;
  if (isNaN(id)) return null;
  return SPORT_NAMES[id] ?? null;
}
